version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew assembleRelease
      - run: mkdir -p apk && mv app/build/outputs/apk/release/app-release.apk apk/
      - run:
          name: Deploy APK to GitHub
          command: |
            git config --global user.email "justinwolff4.11@gmail.com"
            git config --global user.name "Jxxxxn04"
            git add apk/app-release.apk
            git commit -m "Add APK"
            git push origin master
